---

- name: Update every package in every machine and reboot if needed
  hosts: course
  gather_facts: true
  become: true

  tasks:

    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: _reboot_required_file

    - name: Reboot the server (if required).
      ansible.builtin.reboot:
      when: _reboot_required_file.stat.exists

    - name: Remove dependencies that are no longer required.
      ansible.builtin.apt:
        autoremove: yes
