---

ansible_user: ubuntu
ansible_private_key_file: ~/.ssh/id_rsa_aivo_2020

# We use the login node as ssh jump host for every machine in the cluster, also for the login node itself
ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i {{ hostvars["login-node"].ansible_private_key_file }} -W %h:%p -q {{ hostvars["login-node"].ansible_user }}@{{ hostvars["login-node"].ansible_ssh_host }}"'
